HyggeGaming/Pages/DevTeams/GetDevTeams.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;

namespace HyggeGaming.Pages.DevTeams
{
    public class GetDevTeamsModel : PageModel
    {
        public IEnumerable<DevTeam>? DevTeam { get; set; }
        IDevTeamService DevTeamService { get; set; }

        public GetDevTeamsModel(IDevTeamService service)
        {
            DevTeamService = service;
        }

        public void OnGet()
        {
            DevTeam = DevTeamService.GetDevTeams();
        }
    }
}

HyggeGaming/Pages/Teams/CreateTeam.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;

namespace HyggeGaming.Pages.Teams
{ 
    public class CreateTeamModel : PageModel
    {
        private readonly IDevTeamService DevTeamService;
        private readonly IGameService GameService;

        [BindProperty]
        public DevTeam DevTeam { get; set; }
        [BindProperty]
        public Game Game { get; set; }
        public IEnumerable<Game> Games { get; set; }

        public CreateTeamModel(IDevTeamService service, IGameService gService)
        {
            DevTeamService = service;
            GameService = gService;
        }

        public IActionResult OnGet()
        {
            Games = GameService.GetGames();
            return Page();
        }

        public IActionResult OnPost()
        {
            ModelState.Remove("Game.DevelopmentStage");
            ModelState.Remove("Game.GameType");
            ModelState.Remove("Game.GameName");
            if (!ModelState.IsValid)
            {
                return RedirectToPage();
            }

            //Create new team
            DevTeamService.CreateDevTeam(DevTeam);

            //Connect the team with chosen game
            DevTeamService.ConnectTeamWithGame(DevTeam.DevTeamId, Game.GameId);

            return RedirectToPage("/Teams/ManageDevTeams");
        }
    }
}

HyggeGaming/Pages/Teams/GetDevTeams.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;

namespace HyggeGaming.Pages.Teams
{
    public class GetDevTeamsModel : PageModel
    {
        private readonly IDevTeamService DevTeamService;
        public IEnumerable<DevTeam>? DevTeam { get; set; }

        public GetDevTeamsModel(IDevTeamService service)
        {
            DevTeamService = service;
        }

        public void OnGet()
        {
            DevTeam = DevTeamService.GetDevTeams();
        }
    }
}

HyggeGaming/Pages/Teams/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HyggeGaming.Pages.Teams
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HyggeGaming/Pages/Teams/ManageDevTeams.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;

namespace HyggeGaming.Pages.Teams
{
    public class ManageDevTeamsModel : PageModel
    {
        private readonly IDevTeamService DevTeamService;
        private readonly IEmployeeService EmployeeService;

        [BindProperty]
        public DevTeam DevT { get; set; }
        public IEnumerable<DevTeam>? DevTeams { get; set; }
        [BindProperty]
        public Employee Employee { get; set; }
        public IEnumerable<Employee> Employees { get; set; }
        

        [BindProperty (SupportsGet = true)]
        public string? SearchString { get; set; }

        public ManageDevTeamsModel(IDevTeamService service, IEmployeeService empService)
        {
            DevTeamService = service;
            EmployeeService = empService;
        }

        public void OnGet()
        {
            Employees = EmployeeService.GetEmployees();
            DevTeams = DevTeamService.GetDevTeams();

            if (!String.IsNullOrEmpty(SearchString))
            {
                DevTeams = DevTeamService.TeamSearch(SearchString);
            }
            else
            {
                DevTeams = DevTeamService.GetDevTeams();
            } 
        }

        public IActionResult OnPostAssignEmp()
        {

            var teamIdString = Request.Form["DevT.DevTeamId"];
            Console.WriteLine($"Raw Form Value for DevT.DevTeamId: {teamIdString}");

            if (int.TryParse(teamIdString, out int teamId))
            {
                Console.WriteLine($"Parsed DevTeamId: {teamId}");
                DevT.DevTeamId = teamId;
            }
            else
            {
                Console.WriteLine("Invalid input for DevTeamId.");
                return Page();
            }
            EmployeeService.AssignEmpToTeam(Employee, DevT);
            return RedirectToPage();
        }
    }
}

HyggeGaming/Pages/Teams/UpdateDevTeam.cshtml.cs
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace HyggeGaming.Pages.Teams
{
    public class UpdateDevTeamModel : PageModel
    {
        private readonly IDevTeamService DevTeamService;
        [BindProperty]
        public DevTeam? DevT { get; set; }
        public UpdateDevTeamModel(IDevTeamService devTeamService)
        {
            DevTeamService = devTeamService;
        }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Fetch DevTeam using the service
            DevT = DevTeamService.GetDevTeams().FirstOrDefault(t => t.DevTeamId == id.Value);

            if (DevT == null)
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
                // Update DevTeam using the service
                DevTeamService.UpdateDevTeam(DevT);

            return RedirectToPage("/Teams/ManageDevTeams");
        }
    }
}

HyggeGaming/Pages/Teams/CreateTeam.cshtml
@page
@model HyggeGaming.Pages.Teams.CreateTeamModel

@{
    ViewData["Title"] = "CreateTeam";
}
<div class="My-container">
<h1>CreateTeam</h1>

<div class="row justify-content-center">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DevTeam.DevTname" class="control-label"></label>
                <input asp-for="DevTeam.DevTname" class="form-control" />
                <span asp-validation-for="DevTeam.DevTname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Game.GameId">Choose Game</label>
                <select asp-for="Game.GameId" class="form-control">
                    @foreach (var game in Model.Games)
                    {
                        <option value="@game.GameId">@game.GameName</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn myBtn mt-3">Create new team</button>
            </div>
        </form>
    </div>
</div>

    <div>
        <a class="btn backBtn" asp-page="/Teams/ManageDevTeams">Back to team manager</a>
    </div>
</div>

HyggeGaming/Pages/Teams/GetDevTeams.cshtml
@page
@model HyggeGaming.Pages.Teams.GetDevTeamsModel
@{
}


<h1>All teams</h1>
<p>Here is the list of all teams and their employees</p>
<a class="btn myBtn" asp-page="/Employees/Profile">Back to Profile</a>

<div class="table-container">
<table>
    <thead>
        <tr>
            <th>Team Id</th>
            <th>Team Name</th>
            <th>Assigned Game</th>
            <th>Members</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.DevTeam != null)
        {
            @foreach (var team in Model.DevTeam)
            {
                <tr>
                    <td>@team.DevTeamId</td>
                    <td>@team.DevTname</td>
                    <td>
                        @foreach (var manager in team.TeamManagers)
                        {
                            @manager.Game.GameName
                        }
                    </td>
                    <td>
                        <ul class="list-unstyled">
                            @foreach (var member in team.Employees)
                            {
                                <li>
                                    <strong>@member.FirstName @member.LastName</strong>
                                    | @member.Role.Role1 | Email: <a href="mailto:@member.Mail">@member.Mail</a>)
                                </li>
                            }
                        </ul>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
</div>

HyggeGaming/Pages/Teams/ManageDevTeams.cshtml
@page
@model HyggeGaming.Pages.Teams.ManageDevTeamsModel
@{
}

<h1>Manage teams</h1>
<p>This page is your central hub for organizing and managing employee teams within your organization. From here, you can efficiently oversee team structures, assign employees to teams, and ensure smooth collaboration across your workforce.</p>

    <a class="btn backBtn mb-4" asp-page="/Employees/Profile">Back to Profile</a>

<div class="row mb-3">
    <div class="col d-flex">
        <a class="btn myBtn me-2" asp-page="/Teams/CreateTeam">Create new team</a>
        <!--Modal btn-->
        <button type="button" class="btn myBtn" data-bs-toggle="modal" data-bs-target="#editModal_Employee">
            Add employee to a team
        </button>
    </div>
    <div class="col-3 ms-auto text-end">
        <form method="get">
            <div class="form-group d-flex">
                <input type="text" name="SearchString" class="form-control me-2" placeholder="Search teams" value="@Model.SearchString" />
                <button type="submit" class="btn myBtn">Search</button>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal" id="editModal_Employee">
    <div class="modal-dialog">
        <div class="modal-content MyModal">
            <div class="modal-header">
                <h5>Change status for assignment</h5>               
            </div>
            <div class="modal-body">
                <p>
                    Assign employee to a team by choosing employee email and the team. </br>
                    Ïf emplyee already exists in a team, they will be transfered to the chosen team.
                </p>
                <form method="post" asp-page-handler="AssignEmp">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Employee.EmployeeId" /> 
                    <input type="hidden" asp-for="DevT.DevTeamId" /> 

                    <div class="form-group">
                        <label asp-for="@Model.Employee.Mail" class="control-label"></label>
                        <select asp-for="@Model.Employee.Mail" class="form-control">
                            <option value="@Model.Employee">---</option>
                            @foreach (var emp in Model.Employees)
                            {
                                <option value="@emp.Mail">@emp.Mail</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label asp-for="DevT.DevTeamId" class="control-label"></label>
                        <select asp-for="@Model.DevT.DevTeamId" class="form-control">
                            <option>---</option>
                            @foreach (var team in Model.DevTeams)
                            {
                                <option value="@team.DevTeamId">
                                    Team id: (@team.DevTeamId)
                                    @team.DevTname
                                </option>
                            }
                        </select>
                    </div>

                    <div class="form-group mt-2">
                        <button type="submit" value="Save" class="btn myBtn">Save</button>
                        <button type="button" class="btn backBtn" data-bs-dismiss="modal">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                                <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                            </svg>
                        </button>
                    </div>

                </form>

            </div>
        </div>
    </div>
</div>

<div class="table-container">
<table class="table">
    <thead>
        <tr>
            <th>Team Id</th>
            <th>Team Name</th>
            <th>Assigned</th>
            <th>Members</th>
            <th>Actions</th> 
        </tr>
    </thead>
    <tbody>
        @if (Model.DevTeams != null)
        {
            @foreach (var team in Model.DevTeams)
            {
                <tr>
                    <td>@team.DevTeamId</td>
                    <td>@team.DevTname</td>
                    <td>
                        @foreach (var manager in team.TeamManagers)
                        {
                            @manager.Game.GameName
                        }
                    <td>
                        <ul class="list-unstyled">
                            @foreach (var member in team.Employees)
                            {
                                <li>
                                    <strong>@member.FirstName @member.LastName</strong>
                                    | @member.Role.Role1 | Email: <a href="mailto:@member.Mail">@member.Mail</a>
                                </li>
                            }
                        </ul>
                    </td>
                    <td>
                        <a class="btn myBtn" asp-page="/Teams/UpdateDevTeam" asp-route-id="@team.DevTeamId">Edit</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
</div>

HyggeGaming/Pages/Teams/UpdateDevTeam.cshtml
@page
@model HyggeGaming.Pages.Teams.UpdateDevTeamModel
@{
    ViewData["Title"] = "Update Team";
}

<div class="My-container">
<h1>Update Team</h1>

<div class="row justify-content-center">
    <div class="col-md-4">
        <div>
            <p>Change name for team (id: @Model.DevT.DevTeamId, current name: @Model.DevT.DevTname)</p>
        </div>
        <form method="post">
            <input type="hidden" asp-for="DevT"/>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div> 
            <div class="form-group">
                <label asp-for="DevT.DevTeamId" class="control-label"></label>
                <input asp-for="@Model.DevT.DevTeamId" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="@Model.DevT.DevTname" class="control-label"></label>
                <input asp-for="@Model.DevT.DevTname" class="form-control" />
            </div>
           

            <div class="form-group">
                <button type="submit" value="Save" class="btn myBtn">Save changes</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn backBtn" asp-page="/Teams/ManageDevTeams">Back to List</a>
</div>
</div>