HyggeGaming/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HyggeGaming.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    [Column("Employee_ID")]
    public int EmployeeId { get; set; }
     
    [Required(ErrorMessage = "FirstName is required")]
    [StringLength(30)]
    [Unicode(false)]
    public string FirstName { get; set; } = null!;

    [Required(ErrorMessage = "LastName is required")]
    [StringLength(30)]
    [Unicode(false)]
    public string LastName { get; set; } = null!;

    [Required(ErrorMessage = "Address is required")]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; } = null!;

    [Required(ErrorMessage = "ZipCode is required")]
    public int ZipCode { get; set; }

    [Required(ErrorMessage = "Mail is required")]
    [EmailAddress(ErrorMessage = "Invalid Email Address")]
    [StringLength(50)]
    [Unicode(false)]
    public string Mail { get; set; } = null!;

    [Required(ErrorMessage = "Password is required")]
    [StringLength(30)]
    [Unicode(false)]
    public string Password { get; set; } = null!;

    [Required(ErrorMessage = "RoleId is required")]
    [Column("Role_ID")]
    public int RoleId { get; set; }

    [Column("DevTeam_ID")]
    public int? DevTeamId { get; set; }

    [ForeignKey("DevTeamId")]
    [InverseProperty("Employees")]
    public virtual DevTeam? DevTeam { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("Employees")]
    public virtual Role Role { get; set; } = null!;

    [ForeignKey("ZipCode")]
    [InverseProperty("Employees")]
    public virtual City ZipCodeNavigation { get; set; } = null!;
}

HyggeGaming/Pages/Employees/AddEmployee.cshtml.cs
using HyggeGaming.Models;
using HyggeGaming.Services.EFService;
using HyggeGaming.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HyggeGaming.Pages.Employees
{
    public class AddEmployeeModel : PageModel
    {
        private readonly IEmployeeService EmployeeService;
        private readonly ICityService CityService;
        private readonly IRoleService RoleService;

        [BindProperty]           
        public Employee Emp { get; set; }
        public IEnumerable<City> Cities { get; set; }
        public IEnumerable<Role> Roles { get; set; }
        public AddEmployeeModel(IEmployeeService service, ICityService cService, IRoleService rService)
        {
            EmployeeService = service;
            CityService = cService;
            RoleService = rService;
        }

        public IActionResult OnGet()
        {
            Cities = CityService.GetCities();
            Roles = RoleService.GetRoles();
            return Page();
        }

        public IActionResult OnPost(int employeeId)
        {
            //Zipcode connection
            var cityString = Request.Form["Emp.ZipCode"];
            if (int.TryParse(cityString, out int zipcodeInt))
            {
                Console.WriteLine($"Parsed zipcodeInt: {zipcodeInt}");
                Emp.ZipCode = zipcodeInt;
            }
            else
            {
                Console.WriteLine("Invalid input for zipcodeInt.");
                return Page();
            }

            //Role connection
            var roleString = Request.Form["Emp.Role.RoleId"];
            var role = RoleService.GetRoles().FirstOrDefault(r => r.Role1 == roleString); //Denne kan nok godt flyttes til Service, men det virker for nu
            if (role != null)
            {
                Emp.Role = role;
            }
            else
            {
                Console.WriteLine("Invalid input for role.");
                return RedirectToPage();
            }


            //Manually remove fields from validation if needed
            ModelState.Remove("Emp.ZipCodeNavigation");
            ModelState.Remove("Emp.Role.Role1");
            ModelState.Remove("Emp.Role.RoleId");

            if (!ModelState.IsValid)
            {
                return RedirectToPage();
            }
            EmployeeService.AddEmployee(Emp);

            return RedirectToPage("/Employees/AllEmployees", new {successMsg = "New employee has been added successfully"});
        }
    }
}

HyggeGaming/Pages/Employees/AllEmployees.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;
using HyggeGaming.Filters;

namespace HyggeGaming.Pages.Employees
{
    [AuthFilter]
    public class AllEmployeesModel : PageModel
    {
        private readonly IEmployeeService EmployeeService;
        public IEnumerable<Employee>? Employees { get; set; }

        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }

        [BindProperty (SupportsGet = true)]
        public string? successMsg { get; set; }

        public AllEmployeesModel(IEmployeeService context)
        {
            EmployeeService = context;
        }

        public void OnGet()
        {
            if (!String.IsNullOrEmpty(SearchString))
            {
                Employees = EmployeeService.SearchEmployee(SearchString);
            }
            else
                Employees = EmployeeService.GetEmployees();
        }
    }
}

HyggeGaming/Pages/Employees/DeleteEmployee.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;

namespace HyggeGaming.Pages.Employees
{
    public class DeleteEmployeeModel : PageModel
    {
        private readonly IEmployeeService EmployeeService;
        
        [BindProperty]
        public Employee Emp { get; set; }

        public DeleteEmployeeModel(IEmployeeService employeeService)
        {
            EmployeeService = employeeService;
        }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = EmployeeService.GetEmployeeForUpdating(id.Value);

            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Emp = employee;
            }
            return Page();
        }

        public IActionResult OnPost(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = EmployeeService.GetEmployeeForUpdating(id.Value);
            if (employee != null)
            {
                Emp = employee;
                EmployeeService.DeleteEmployee(Emp);
            }

            return RedirectToPage("/Employees/AllEmployees");
        }
    }
}

HyggeGaming/Pages/Employees/Login.cshtml.cs
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HyggeGaming.Pages.Employees
{
    public class LoginModel : PageModel
    {
        private readonly IEmployeeService EmployeeService;

        [BindProperty]
        public Employee Employee { get; set; }

        public string ErrorMsg = string.Empty;

        public LoginModel(IEmployeeService service)
        {
            EmployeeService = service;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public IActionResult OnPost()
        {            
            if (EmployeeService.CheckCredentials(Employee))
            {
                HttpContext.Session.SetString("LoggedIn", Employee.Mail);
                return RedirectToPage("/Employees/Profile");
            }
            else
            {               
                ErrorMsg = "Incorrect email or password";
                return Page();
            }
        }
    }
}

HyggeGaming/Pages/Employees/Profile.cshtml.cs
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HyggeGaming.Pages.Employees
{
    public class ProfileModel : PageModel
    {
        private readonly IEmployeeService EmployeeService;
        private readonly IAssignmentService AssignmentService;
        public string ErrorMessage { get; set; }

        [BindProperty]
        public Employee? Employee { get; set; }

        [BindProperty]
        public Game Game { get; set; }
        [BindProperty]
        public Assignment assignment { get; set; }
        [BindProperty]
        public IEnumerable<Assignment> Assignments { get; set; }
        public List<string> Statuses { get; set; }
        public IEnumerable<Employee> Employees { get; set; }

        public ProfileModel(IEmployeeService service, IAssignmentService aService)
        {
            EmployeeService = service;
            AssignmentService = aService;
        }

        public IActionResult OnGet()
        {
            var loggedInEmployee = HttpContext.Session.GetString("LoggedIn");

            if (!string.IsNullOrEmpty(loggedInEmployee))
            {
                Employee = EmployeeService.GetEmployee(loggedInEmployee);
                
            }

            if (Employee != null)
            {
                Employees = EmployeeService.GetTeamMembers(Employee);
                
                var teamManagers = Employee.DevTeam?.TeamManagers;
                if(teamManagers != null)
                {
                    Game = teamManagers.FirstOrDefault()?.Game;
                    Assignments = Game?.Assignments;
                    Statuses = AssignmentService.Statuses();
                }
                
                return Page();
            }

            return RedirectToPage("/Employees/Login");
        }

        public IActionResult OnPost(int employeeId)
        {   
                //Manually remove fields from validation if needed
                ModelState.Remove("Emp.ZipCodeNavigation");
                ModelState.Remove("Emp.Role");

                if (!ModelState.IsValid)
                {
                    
                    return Page();
                }
                EmployeeService.UpdateEmployee(Employee);

                return RedirectToPage("/Employees/Profile");

        }

        public IActionResult OnPostEdit()
        {
            //Ingen ModelState validation fordi det kun er et felt som opdateres og dette er en dropdown
            AssignmentService.UpdateAssignment(assignment);

            return RedirectToPage();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Employees/Login");
        }

        public IActionResult OnPostChangePassword(int employeeId, string newPassword, string confirmPassword)
        {

            if (newPassword == confirmPassword)
            {
                Employee = EmployeeService.GetEmployeeForUpdating(employeeId);
                if (Employee != null)
                {
                    Employee.Password = newPassword;
                    EmployeeService.UpdateEmployee(Employee);
                }

                return RedirectToPage("/Employees/Profile");
            }
            else
            {
                var loggedInEmployee = HttpContext.Session.GetString("LoggedIn");

                if (!string.IsNullOrEmpty(loggedInEmployee))
                {
                    Employee = EmployeeService.GetEmployee(loggedInEmployee);
                }

                ErrorMessage = "Password not changed - make sure passwords are identical";
                return Page();
            }

        }
    }
}

HyggeGaming/Pages/Employees/UpdateEmployee.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HyggeGaming.Models;
using HyggeGaming.Services.Interfaces;
namespace HyggeGaming.Pages.Employees
{
    public class UpdateEmployeeModel : PageModel
    {

        private readonly IEmployeeService EmployeeService;
        private readonly IDevTeamService DevTeamService;
        private readonly IRoleService RoleService;
        private readonly ICityService CityService;

        [BindProperty]
        public Employee Emp { get; set; }

        public IEnumerable<City> Cities { get; set; }
        public IEnumerable<Role> Roles { get; set; }

        public UpdateEmployeeModel(IEmployeeService empService, IDevTeamService teamService, IRoleService roleService, ICityService cityService)
        {
            EmployeeService = empService;
            DevTeamService = teamService;
            RoleService = roleService;
            CityService = cityService;
        }

        public IActionResult OnGet(int? employeeId)
        {

            if (employeeId == null)
            {
                return NotFound();
            }

            // Fetch the employee with related data
            Emp = EmployeeService.GetEmployeeForUpdating(employeeId.Value);

            if (Emp == null)
            {
                return NotFound();
            }

            Cities = CityService.GetCities();
            Roles = RoleService.GetRoles();

            return Page();
        }

        public IActionResult OnPost(int employeeId)
        {
            //Zipcode connection
            var cityString = Request.Form["Emp.ZipCode"];
            if (int.TryParse(cityString, out int zipcodeInt))
            {
                Console.WriteLine($"Parsed zipcodeInt: {zipcodeInt}");
                Emp.ZipCode = zipcodeInt;
            }
            else
            {
                Console.WriteLine("Invalid input for zipcodeInt.");
                return RedirectToPage();
            }

            //Role connection
            var roleIdString = Request.Form["Emp.RoleId"];
            if (int.TryParse(roleIdString, out int roleId))
            {
                Emp.RoleId = roleId; // Directly set RoleId
            }
            
            else
            {
                Console.WriteLine("Invalid input for role.");
                return RedirectToPage();
            }

            //Manually remove fields from validation if needed
            ModelState.Remove("Emp.ZipCodeNavigation");
            ModelState.Remove("Emp.Role.Role1");
            ModelState.Remove("Emp.Role.RoleId");
            ModelState.Remove("Emp.Role");

            if (!ModelState.IsValid)
            {
                return RedirectToPage();
            }
            EmployeeService.UpdateEmployee(Emp);

            return RedirectToPage("/Employees/AllEmployees");
        }
    }
}

HyggeGaming/Pages/Employees/AddEmployee.cshtml
@page
@model HyggeGaming.Pages.Employees.AddEmployeeModel
@{
    ViewData["Title"] = "AddEmployee";
}

<div class="My-container">
<h1 class="ms-5">Add Employee</h1>

<div class="row justify-content-center">
    <div class="col-md-4">
        <form method="post">
           
            <div class="form-group">
                <label asp-for="@Model.Emp.FirstName" class="control-label"></label>
                <input asp-for="@Model.Emp.FirstName" class="form-control" />
                <span asp-validation-for="Emp.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Emp.LastName" class="control-label">LastName</label>
                <input asp-for="@Model.Emp.LastName" class="form-control" />
                <span asp-validation-for="Emp.LastName" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="@Model.Emp.Address" class="control-label">Address</label>
                <input asp-for="@Model.Emp.Address" class="form-control" />
                <span asp-validation-for="Emp.Address" class="text-danger"></span>
            </div>           
            <div class="form-group"> @*Zipcode/city dropdown*@
                <label asp-for="@Model.Emp.ZipCode" class="control-label">ZipCode</label>
                <select asp-for="@Model.Emp.ZipCode" class="form-control">
                    <option value="">Choose zipcode</option>
                    @foreach (var zip in Model.Cities)
                    {
                        <option value="@zip.ZipCode">@zip.ZipCode @zip.City1</option>
                    }                    
                </select>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Emp.Mail" class="control-label">Mail</label>
                <input asp-for="@Model.Emp.Mail" class="form-control" />
                <span asp-validation-for="Emp.Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Emp.EmployeeId" class="control-label">Id</label>
                <input asp-for="@Model.Emp.EmployeeId" class="form-control" />
                <span asp-validation-for="Emp.EmployeeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.Emp.Password" class="control-label">Password</label>
                <input asp-for="@Model.Emp.Password" class="form-control" />
                <span asp-validation-for="Emp.Password" class="text-danger"></span>
            </div>
            
            <div class="form-group"> @*Add role dropdown*@
                <label asp-for="@Model.Emp.Role.RoleId" class="control-label">Role</label>
                <select asp-for="@Model.Emp.Role.RoleId" class="form-control">
                    <option value="">Choose role</option>
                    @foreach (var role in Model.Roles)
                    {
                        <option value="@role.Role1">@role.Role1</option>
                    }
                </select>
            </div>
            @*Add team dropdown*@
            <div class="form-group visually-hidden">
                <label asp-for="@Model.Emp.DevTeamId" class="control-label">Team Id</label>
                <input asp-for="@Model.Emp.DevTeamId" class="form-control" />
                <span asp-validation-for="Emp.DevTeam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn myBtn mt-3">Add new employee</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="ms-5 btn backBtn" asp-page="/Employees/AllEmployees">Back to List</a>

</div>
</div>

HyggeGaming/Pages/Employees/Profile.cshtml
@page
@model HyggeGaming.Pages.Employees.ProfileModel
@{
}

<div class="m-2">
    <h1>Profile & workspace</h1>
</div>

@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@Model.ErrorMessage</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="row d-flex align-items-start">
    <div class="col-3 My-container align-content-center">
        <div>
            <img class="profile-img" src="~/img/ProfileOtter.png" />
        </div>

        <div class="form-like">
            <span class="fake-label">Employee ID:</span>
            <span class="fake-input">@Model.Employee.EmployeeId</span>
        </div>
        <div class="form-like">
            <span class="fake-label">Full Name:</span>
            <span class="fake-input">@Model.Employee.FirstName @Model.Employee.LastName</span>
        </div>
        <div class="form-like">
            <span class="fake-label">Email:</span>
            <span class="fake-input">@Model.Employee.Mail</span>
        </div>
        <div class="form-like">
            <span class="fake-label">Full Address:</span>
            <span class="fake-input">@Model.Employee.Address, @Model.Employee.ZipCode @Model.Employee.ZipCodeNavigation.City1</span>
        </div>

        <div class="form-like">
            <span class="fake-label">Password:</span>
                <input type="password" value="@Model.Employee.Password"
                       class="fake-input password-field" />
                <button class="btn myBtn mt-3" data-bs-toggle="modal" data-bs-target="#updatePasswordModal">
                    <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                        <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001m-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708z" />
                    </svg>
                </button>
        </div>       
    </div>

    <div class="col-8">
        <div class="form-like">
            <span class="fake-label">Role</span>
            <span class="fake-input">@Model.Employee.Role.Role1</span>
        </div>
        <div class="form-like">
            @if (Model.Employee.DevTeam != null)
            {
                <h3>Team @Model.Employee.DevTeam.DevTname:</h3>

                <span class="fake-label">Team members:</span>

                <div class="fake-input">

                    @if (Model.Employees != null)
                    {
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var member in Model.Employees)
                                {
                                    <tr>
                                        <td>@member.FirstName @member.LastName</td>
                                        <td>@member.Mail</td>
                                        <td>@member.Role?.Role1</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }

                </div>
            }
            
        </div> 

        @if (Model.Game != null)
        {
        <h4>Assignments for @Model.Game.GameName</h4>

        <div class="row justify-content-evenly">
            @if (Model.Assignments != null)
            {
                @foreach (var item in Model.Assignments)
                {
                    <div class="col-12 col-sm-6 col-lg-3 m-2">
                        <div class="fake-input p-1">
                            <h4>@item.AssignmentName</h4>
                            <p>@item.Description</p>
                            <p>Status: @item.Status</p>
                            <div class="card-footer">
                                <!--Modal btn-->
                                <button type="button" class="btn myBtn" data-bs-toggle="modal" data-bs-target="#editModal_@item.AssignmentId">
                                    Change status
                                </button>
                            </div>
                        </div>
                    </div>


                        <!-- Modal -->
                        <div class="modal" id="editModal_@item.AssignmentId">
                            <div class="modal-dialog">
                                <div class="modal-content MyModal">
                                    <div class="modal-header">
                                        <h5>Change status for assignment</h5>
                                    </div>
                                    <div class="modal-body">

                                        <form method="post" asp-page-handler="Edit">
                                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                            <input type="hidden" asp-for="@item.AssignmentId" name="assignment.AssignmentId" />

                                            <div class="form-group">
                                                <label asp-for="@item.AssignmentName" class="control-label"></label>
                                                <input asp-for="@item.AssignmentName" name="assignment.AssignmentName" class="form-control" disabled />
                                            </div>

                                            <div class="form-group">
                                                <label asp-for="@item.Description" class="control-label"></label>
                                                <input asp-for="@item.Description" name="assignment.Description" class="form-control" disabled />
                                            </div>

                                            <div class="form-group">
                                                <label asp-for="@item.Status" class="control-label"></label>
                                                <select asp-for="@item.Status" name="assignment.Status" class="form-control">
                                                    <option value="@item.Status">---</option>
                                                    @foreach (var status in Model.Statuses)
                                                    {
                                                        <option value="@status">@status</option>
                                                    }
                                                </select>
                                            </div>

                                            <div class="form-group mt-2">
                                                <button type="submit" value="Save" class="btn myBtn">Save</button>
                                                <button type="button" class="btn backBtn" data-bs-dismiss="modal">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                                                        <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
                                                    </svg>
                                                </button>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                }
            }
            else
            {
                <p>No assignments available for this game.</p>
            }
            </div>
        }
        
        @*Kommentar*@
        <div class="d-flex justify-content-between pt-5 mt-5">
            <div class="container fake-input me-3 flex-fill">
                <h4>Important Resources</h4>
                <p>Access essential tools and documents to support your work. Explore policies, training materials, and other helpful resources:</p>
                <ul>
                    <li><a href="/policies">Company Policies</a></li>
                    <li><a href="/handbook.pdf" target="_blank">Employee Handbook</a></li>
                    <li><a href="/training">Training Modules</a></li>
                </ul>
            </div>

            <div class="container fake-input flex-fill">
                <h4>Support and IT Help</h4>
                <p>If you need assistance, you can:</p>
                <ul>
                    <li><a href="/support/faq">Browse the FAQ</a></li>
                    <li><a href="/support/ticket">Submit a Support Request</a></li>
                    <li>Email us at: <a href="mailto:support@company.com">support@company.com</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>


@*SideNav - !Admin*@
@if (Model.Employee.RoleId != 1)
{
    <div class="sidenav">
        <a asp-page="/Games/ViewGames">All Games</a>
        <a asp-page="/Teams/GetDevTeams">All Teams</a>

        <div class="logout-container align-bottom">
            <form method="Post" asp-page-handler="Logout" class="d-inline">
                <button type="submit" class="btn btn-outline-dark">
                    <img src="~/img/logout.png"class="logout-img p-4" /> 
                </button>
            </form>
        </div>
    </div>
}

@*SideNav - admin*@
@if (Model.Employee.RoleId == 1)
{
    <div class="sidenav">
        <a asp-page="/Employees/AllEmployees">Manage Employees</a>
        <a asp-page="/Games/ManageGames">Manage Games</a>
        <a asp-page="/Teams/ManageDevTeams">Manage Teams</a>
        <a asp-page="/Assignments/AllAssignments">Manage Assignments</a>

        <div class="logout-container align-bottom">
            <form method="Post" asp-page-handler="Logout" class="d-inline">
                <button type="submit" class="btn btn-outline-dark">
                    <img src="~/img/logout.png" class="logout-img p-4" />
                </button>
            </form>
        </div>
    </div>
}

@*Change password modal*@
<div class="modal fade" id="updatePasswordModal" tabindex="-1" aria-labelledby="updatePasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content MyModal">
            <div class="modal-header">
                <h5 class="modal-title" id="updatePasswordModalLabel">Update Password</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-page-handler="ChangePassword">
                <div class="modal-body">
                    <input type="hidden" name="employeeId" value="@Model.Employee.EmployeeId" />
                    <div class="mb-3">
                        <label for="newPassword" class="form-label">New Password</label>
                        <input type="password" class="form-control" id="newPassword" name="NewPassword" required maxlength="30" />
                    </div>
                    <div class="mb-3">
                        <label for="confirmPassword" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="confirmPassword" name="ConfirmPassword" required maxlength="30" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn backBtn" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn myBtn">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>